### ISSUE TITLE
Post Model

### ISSUE THREAD

**Issue by Cushione** [Cushione/photora_api#12]
## Tasks
- [x] Create Post app
- [x] Create Post model
- [x] Create Post serializer
