### ISSUE TITLE
Comment Model

### ISSUE THREAD

**Issue by Cushione** [Cushione/photora_api#14]
## Tasks

- [x] Add Comment App
- [x] Add Comment Model
- [x] Add Comment Serializer
